### ISSUE TITLE
Print first message, when dropping messages due to overload

### ISSUE THREAD

**Issue by tomekowal** [josevalim/logger#9]
Hi! Now when I have cascading errors, I don't see what was the cause, because all errors can be hidden. Maybe it would be good to print first one and then drop rest?

If it sounds like a good idea, I can make a pull request.

**Comment by josevalim** [comment]
Thank you! How can we know it was the first? It is a concurrent system,
messages can come for everywhere, at anytime!

## 

_José Valim_
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by tomekowal** [comment]
Yes, I meant first one, that is in the `error_handler` message queue. I understand that it might not be the first one actually sent to the process, but as you said - it is a distributed system.

Currently I am receiving the alert, that 500 OTP messages were dropped. I see this alert couple of times, the app is still working, but there is no actual error printed anywhere. I am just having a bad luck and the logs are delivered in bursts, so Logger doesn't actually print any of them.

I saw, that checking the threshold is done here: https://github.com/elixir-lang/elixir/blob/master/lib/logger/lib/logger/error_handler.ex#L81 I think that in case of overload, I can simply log the first message from the queue and then clear the queue. This would at least give me idea where to look for the problem.

EDIT: I think, I should have put this on https://github.com/elixir-lang/elixir Sorry for the confusion.

**Comment by josevalim** [comment]
@tomekowal HA. Just now I noticed it was in the `logger` project. We already print the first message, it is the event we are currently processing:

https://github.com/elixir-lang/elixir/blob/master/lib/logger/lib/logger/error_handler.ex#L25-L29

Other than that, there is no guarantee the first message being dropped is the one we want.There is also a high chance the first message is already logged anyway. Let's try two things though:
1. Try increasing the threshold size and see if your node will still be fine, so you get a bit more tolerance for that
2. Try patching Elixir to not drop the first message, run it in production, and let us know if it improves things

But the first message should be the one being currently processed, assuming nothing else was happening. Thank you!

**Comment by tomekowal** [comment]
Thank you, now I see that at least one event should be logged. Looks like we messed up something with logging on the application side and logger works exactly as we want it to.
Thanks again!
